### ISSUE TITLE
Working With Mimic?

### ISSUE THREAD

**Issue by ryanleesipes** [peterdrysdale/bellbird#4]
Hey, this is not the right way to do this but I couldn't any other way to get you @peterdrysdale 

Do you have any interest in working with the Mimic project? Many of our goals align with Bellbird and we just realized that your project exists.

Check it out, we could really use your expertise and contribution: https://mimic.mycroft.ai - also feel free to hit me up on IRC, #mycroft on Freenode.

**Comment by peterdrysdale** [comment]
E-mail address sent via IRC. Closing issue.
